### ISSUE TITLE
Connection Closed instantly

### ISSUE THREAD

**Issue by bunower** [roke22/Laravel-ssh-client#17]
Hi there,
i try to get Laravel SSH-Client working.
But when i try to connect to server it instantly gives an error `connection closed`.
```
root@evilcorp:/var/www/html/evilcorp-ssh# php ssh-server/bin/websocket.php 2>&1 >/dev/null &
[1] 15887
root@evilcorp:/var/www/html/evilcorp-ssh# PHP Fatal error:  Uncaught Error: Call to undefined function MyApp\ssh2_connect() in /var/www/html/evilcorp-ssh/ssh-server/src/Servidorsocket.php:109
Stack trace:
#0 /var/www/html/evilcorp-ssh/ssh-server/src/Servidorsocket.php(67): MyApp\Servidorsocket->connectSSH()
#1 /var/www/html/evilcorp-ssh/ssh-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(75): MyApp\Servidorsocket->onMessage()
#2 /var/www/html/evilcorp-ssh/ssh-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(131): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#3 /var/www/html/evilcorp-ssh/ssh-server/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#4 /var/www/html/evilcorp-ssh/ssh-server/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#5 /var/www/html/evilcorp-ssh/ssh-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(153): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#6 /var/www/html/evilcorp-ssh/ssh-server/vendor/cboden/ratchet/src/Ratchet/Http/HttpServer.php(54): Ratchet\WebSocket\WsServer->onMessage()
#7 /var/www/html/evilcorp-ssh/ssh-server/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(112): Ratchet\Http\HttpServer->onMessage()
#8 /var/www/html/evilcorp-ssh/ssh-server/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(95): Ratchet\Server\IoServer->handleData()
#9 /var/www/html/evilcorp-ssh/ssh-server/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\Server\IoServer->Ratchet\Server\{closure}()
#10 /var/www/html/evilcorp-ssh/ssh-server/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#11 /var/www/html/evilcorp-ssh/ssh-server/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#12 /var/www/html/evilcorp-ssh/ssh-server/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit()
#13 /var/www/html/evilcorp-ssh/ssh-server/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData()
#14 /var/www/html/evilcorp-ssh/ssh-server/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#15 /var/www/html/evilcorp-ssh/ssh-server/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#16 /var/www/html/evilcorp-ssh/ssh-server/bin/websocket.php(38): Ratchet\Server\IoServer->run()
#17 {main}
  thrown in /var/www/html/evilcorp-ssh/ssh-server/src/Servidorsocket.php on line 109
```
On developer console it says:
```
WebSocket connection to 'wss://wss.evilcorp.de:8090/' failed: 
connectServer @ 1:33
decrypt @ 1:98
```

**Comment by roke22** [comment]
Hello,
If you are running on linux machine you need to install php-ssh2. If you
are on windows you must search the php-ssh2 package. You can view if you
have installed with "phpinfo()".
Jose J. Anton

**Comment by bunower** [comment]
> Hello, If you are running on linux machine you need to install php-ssh2. If you are on windows you must search the php-ssh2 package. You can view if you have installed with "phpinfo()". 
tyvm
